spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12796455
#    url: jdbc:mysql://mysql-db:3306/test
#    url: jdbc:mysql://localhost:3306/test
    username: sql12796455
    password: NehErjhFkr
#    username: root
#    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    hikari:
      maximum-pool-size: 10
  application:
    name: learn
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    enabled: true

default:
  theme: EAE21D
  display-image: /profilePics/defaultDP.jpg

server:
  address: 0.0.0.0
  port: 7071
  error:
    whitelabel:
      enabled: false  # Disable the default error page
    include-message: always  # Always include error message in the response
    include-binding-errors: always  # Always include binding errors in the response


logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.hibernate: DEBUG
    com.com.gmi.learn: DEBUG


